version: '3.1'

services:
  matgbot:
    depends_on:
      - matgbotdb
    ports:
      - '8080:8080'
    expose:
      - '8080'
    build:
      context: .
    networks:
      - mynetwork
    container_name: 'matgbot'
    restart: always
  matgbotdb:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'matgbot_db_user'
      MYSQL_PASSWORD: '0RrQZF52mROh'
      MYSQL_DATABASE: 'matgbot_db'
      MYSQL_ROOT_PASSWORD: 'Mangalibholo18'
    container_name: 'matgbotdb'
    networks:
      - mynetwork
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  mynetwork: