version: '3.1'

services:
  matgbot-db:
    image: mysql
    restart: always
    container_name: matgbot_db
    environment:
      MYSQL_DATABASE: 'matgbot_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'matgbot_db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'matgbot_db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Mangalibholo18'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'