version: '3.1'

services:
  matgbot:
    depends_on:
      - matgbot-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  matgbot-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'matgbot_db'
      MYSQL_ROOT_PASSWORD: 'Mangalibholo18'
    ports:
      - '3307:3306'
    expose:
      - '3307'
